stages:
  data_ingestion:
    cmd: python src/mlproject/pipeline/stage_01_data_ingestion.py
    deps:
      - src/mlproject/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/winequality-red.csv

  data_validation:
    cmd: python src/mlproject/pipeline/stage_02_data_validation.py
    deps:
      - src/mlproject/pipeline/stage_02_data_validation.py
      - config/config.yaml
      - schema.yaml
    outs:
      - artifacts/data_validation/status.txt

  data_transformation:
    cmd: python src/mlproject/pipeline/stage_03_data_transformation.py
    deps:
      - src/mlproject/pipeline/stage_03_data_transformation.py
      - config/config.yaml
      - artifacts/data_ingestion/winequality-red.csv
    outs:
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv


  model_trainer:
    cmd: python src/mlproject/pipeline/stage_04_model_trainer.py
    deps:
      - src/mlproject/pipeline/stage_04_model_trainer.py
      - config/config.yaml
      - params.yaml
      - schema.yaml
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv
    params:
      - ElasticNet.alpha
      - ElasticNet.l1_ratio
    outs:
      - artifacts/model_trainer/model.joblib

  model_evaluation:
    cmd: python src/mlproject/pipeline/stage_05_model_evaluation.py
    deps:
      - src/mlproject/pipeline/stage_05_model_evaluation.py
      - config/config.yaml
      - params.yaml
      - schema.yaml
      - artifacts/data_transformation/test.csv
      - artifacts/model_trainer/model.joblib
    params:
      - ElasticNet.alpha
      - ElasticNet.l1_ratio
    # outs:
    #   - artifacts/model_evaluation/metrics.json
    metrics:
    - artifacts/model_evaluation/metrics.json:
        cache: false

  